const visibleChartsTypes = {
    ADD_CHART_TO_DISPLAY: 'ADD_CHART_TO_DISPLAY',
    REMOVE_CHART_FROM_DISPLAY: 'REMOVE_CHART_FROM_DISPLAY',
    DISPLAY_DEFAULT_CHARTS: 'DISPLAY_DEFAULT_CHARTS',
    SET_CHARTS_TO_DISPLAY: 'SET_CHARTS_TO_DISPLAY',
    SET_DISPLAY_ORDER_OF_CHARTS: 'SET_DISPLAY_ORDER_OF_CHARTS',
    REPLACE_CHART_TO_DISPLAY: 'REPLACE_CHART_TO_DISPLAY'
}

export default visibleChartsTypes;