const kundaliSettings = {
    SET_AYANAMSHA: 'SET_AYANAMSHA',
    SET_ZODIAC_TYPE: 'SET_ZODIAC_TYPE',
    SET_HOUSE_TYPE: 'SET_ZODIAC_TYPE',
    SET_NODE_TYPE: 'SET_NODE_TYPE',
    SET_KUNDALI_SETTINGS: 'SET_KUNDALI_SETTINGS'
}

export default kundaliSettings;