const currentUserTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_ALL_USER_KUNDALIS: 'SET_ALL_USER_KUNDALIS',
    EDIT_SAVED_KUNDALI: 'EDIT_SAVED_KUNDALI',
    ADD_NEW_KUNDALI_TO_ALL_USER_KUNDALIS: 'ADD_NEW_KUNDALI_TO_ALL_USER_KUNDALIS'
}

export default currentUserTypes;