const kundaliTypes = {
    FETCH_KUNDALI_FROM_SERVER_START: 'FETCH_KUNDALI_FROM_SERVER_START',
    FETCH_KUNDALI_FROM_SERVER_SUCCESS: 'FETCH_KUNDALI_FROM_SERVER_SUCCESS',
    FETCH_KUNDALI_FROM_SERVER_FAILURE: 'FETCH_KUNDALI_FROM_SERVER_FAILURE'
}

export default kundaliTypes;